edits

diff --git a/database/20240704164832-ae846f0d186e581bb7aa/subcommands/cleanup b/database/20240704164832-ae846f0d186e581bb7aa/subcommands/cleanup
--- a/database/20240704164832-ae846f0d186e581bb7aa/subcommands/cleanup
+++ b/database/20240704164832-ae846f0d186e581bb7aa/subcommands/cleanup
@@ -1,9 +1,11 @@
 #!/bin/bash
 
-tf=$(mktemp)
-if [ -z "$tf" ]; then exit 1; fi
-
 # clean up empty directories
+# this is primarily for dealing with git leaving empty directories laying around when reverting changes
+
+tf=$(mktemp)
+if [ -z "$tf" ]; then exit 1; fi # failed to allocate temp file
+
 find database -type d -empty | awk -F / 'NF == 2' > $tf
 lines=$(wc -l $tf | awk '{print $1}')
 if [ $lines -gt 0 ]; then
